## Group User

### Create User [/user/]

#### Create a user [POST]

Creates new user object.

+ Request (application/json)

        {
            "email": "<%= user.email %>",
            "firstName": "<%= user.firstName %>",
            "lastName": "<%= user.lastName %>"
        }

+ Response 201 (application/json)

        {
            "status": "success",
            "code": 201,
            "apiVersion": 1,
            "requestUrl": "<%= api.url %>/user/",
            "data": {
                "id": 1,
                "link": "<%= api.url %>/user/1/",
                "rel": "self",
                "value": {
					"email": "<%= user.email %>",
		            "firstName": "<%= user.firstName %>",
		            "lastName": "<%= user.lastName %>",
                    "createDate": <%= timestamp %>
                }
            }
        }

### Manage User [/user/{userId}/]

The parameter `userId` is part of the URL.

#### Get a user [GET]

Returns a user object.

+ Parameters
    + userId (required, numeric, `1`) ... ID of the User

+ Response 200 (application/json)

        {
            "status": "success",
            "code": 200,
            "apiVersion": 1,
            "requestUrl": "<%= api.url %>/user/1/",
            "data": {
                "id": 1,
                "link": "<%= api.url %>/user/1/",
                "rel": "self",
                "value": {
                    "email": "<%= user.email %>",
                    "firstName": "<%= user.firstName %>",
                    "lastName": "<%= user.lastName %>",
                    "createDate": <%= timestamp %>
                }
            }
        }

#### Update a user [PUT]

Updates user data.

+ Parameters
    + userId (numeric, required, `1`) ... ID of the User
    + firstname (string, optional, `<%= user.firstName %>`) ... User's first name
    + lastname (string, optional, `<%= user.lastName %>`) ... User's last name
    + email (string, optional) ... User's email address

+ Response 200 (application/json)

        {
            "status": "success",
            "code": 200,
            "apiVersion": 1,
            "requestUrl": "<%= api.url %>/user/1/",
            "data": {}
        }

### Delete a user [DELETE]

Deletes a user.

+ Parameters
    + userId (numeric, required, `1`) ... ID of the User

+ Response 204 (application/json)

        {
            "status": "success",
            "code": 204,
            "message": null,
            "apiVersion": 1,
            "requestUrl": "<%= api.url %>/user/1/",
            "data": {}
        }
